/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l552.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static uint32_t stack_size = 0;

int main(void)
{
	while (1)
	{
		__asm volatile ("POP {R0}");
		stack_size++;
	}

	/* Loop forever */
	for (;;);
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	printf("The stack size was %lu words - %lu bytes.\n", stack_size, stack_size * 4);
	while(1);
}
