/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int value = 42;
	int *ptr;

	ptr = &value;
	printf("value %d ,&value 0x%x,\t*ptr %d ptr 0x%x\n", value, &value, *ptr, ptr);
	*ptr = 100;    // Changes value to 100 through the pointer
	printf("value %d ,&value 0x%x,\t*ptr %d ptr 0x%x\n", value, &value, *ptr, ptr); // Prints 100
    /* Loop forever */
	for(;;);
}
