/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l552.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHB2ENR.GPIOBEN = ENABLED;
//	GPIOB->MODER.MODER7 = RESET_MODE;
	GPIOB->MODER.MODER7 = OUTPUT_MODE;
	GPIOB->ODR.ODR7 = ON;

    while(1)
    {
    	GPIOB->ODR.ODR7 = ~GPIOB->ODR.ODR7;

    	// Delay (volatile counter prevents optimization):
    	for (volatile uint32_t i = 0; i < 100000; i++);
    }
}
