/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l552.h"
#include "NVIC_registers.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define FIRST_IRQ    62  /* USART2 IRQ number */
#define SECOND_IRQ     61  /* USART1 IRQ number */

/* Interrupt state tracking */
volatile uint32_t g_first_entry_count = 0;
volatile uint32_t g_first_exit_count = 0;
volatile uint32_t g_second_entry_count = 0;
volatile uint32_t g_second_exit_count = 0;

/**
 * Second Interrupt Handler
 */
void USART1_IRQHandler(void) {
    // Track entry:
    g_second_entry_count++;

    printf("Entered to second interrupt.\n");

    // Clear the pending interrupt:
//    NVIC_ClearPendingIRQ(SECOND_IRQ);

    // Track exit:
    g_second_exit_count++;

    printf("Exited from second interrupt.\n");
}


/**
 * First Interrupt Handler
 */
void USART2_IRQHandler(void) {
    // Track entry:
    g_first_entry_count++;

    printf("Entered to first interrupt.\n");

    // Clear the pending interrupt:
    NVIC_ClearPendingIRQ(FIRST_IRQ);

    // Trigger the second interrupt:
	printf("Triggering second interrupt...\n");
	NVIC_SetPendingIRQ(SECOND_IRQ);

    // Clear the pending second interrupt:
	NVIC_ClearPendingIRQ(SECOND_IRQ);

    // Track exit:
    g_first_exit_count++;

    printf("Exited from first interrupt.\n");
}

int main(void)
{
	printf("Calling second interrupt from first interrupt, then clear before this will run demo:\n");

	// Configure priorities - LOWER number means HIGHER priority:
	NVIC_SetPriority(FIRST_IRQ, 1); /* Higher priority (lower number) */
	NVIC_SetPriority(SECOND_IRQ, 2);  /* Lower priority (higher number) */

	// Enable both interrupts:
	NVIC_EnableIRQ(FIRST_IRQ);
	NVIC_EnableIRQ(SECOND_IRQ);

    // Trigger primary interrupt:
	printf("Triggering first interrupt...\n");
	NVIC_SetPendingIRQ(FIRST_IRQ);

	printf("First interrupt has been entered %ld times and exited %ld times.\n",
			g_first_entry_count, g_first_exit_count);
	printf("Second interrupt has been entered %ld times and exited %ld times.\n",
			g_second_entry_count, g_second_exit_count);

    /* Loop forever */
    printf("Demo complete. Entering infinite loop.\n");
    for(;;);
}
