/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l552.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	while (1)
	{
		__asm volatile ("PUSH {R0}");
	}

	/* Loop forever */
	for (;;);
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Mem Manage fault detected\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Bus fault detected\n");
	while(1);
}

void UsageFault_Handler(void)
{
	printf("Usage fault detected\n");
	while(1);
}

void SecureFault_Handler(void)
{
	printf("Secure fault detected\n");
	while(1);
}
