/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l552.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void change_access_level_priv(void)
{

	//read
	__asm volatile ("MRS R0,CONTROL");
	//modify
	__asm volatile ("BFC R0,#0,#1");
	//write
	__asm volatile ("MSR CONTROL,R0");

}

void change_access_level_unpriv(void)
{

	//read
	__asm volatile ("MRS R0,CONTROL");
	//modify
	__asm volatile ("ORR R0,R0,#0x01");
	//write
	__asm volatile ("MSR CONTROL,R0");

}

__attribute__((naked)) void trigger_svc(void)
{
    __asm volatile ("SVC #0");
    __asm volatile ("BX LR");
}

void SVC_Handler(void)
{
    change_access_level_priv();
}

int main(void)
{
	printf("In thread mode : before interrupt\n");

	change_access_level_unpriv();

	void (*fun_ptr)(void);

	/* storing some address in the function pointer variable */
	fun_ptr = change_access_level_unpriv;
//	fun_ptr = (void (*)(void))0x80002cc;
//	fun_ptr = (void (*)(void))0x80002cd;

	/* Here the address  gets copied into PC
	 * 0th bit of the address will be copied into T bit.
	 * Since the 0th bit is 0, T bit becomes 0 which raises processor fault */
	fun_ptr();

	trigger_svc(); // For change back to privileged mode.
	printf("In thread mode : after interrupt\n");

	/* Loop forever */
	for (;;);
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}
